
source 'http://rubygems.org'

gem 'sinatra', '~> 1.4', '>= 1.4.7'
gem 'sinatra-contrib', '~> 1.4', '>= 1.4.6'
gem 'rake'
gem 'data_mapper'
gem 'dm-core'
gem 'dm-sqlite-adapter'
gem 'dm-timestamps'
gem 'dm-validations'
gem 'dm-aggregates'
gem 'dm-migrations'

